// tests/root-entries.test.mjs
//
// Regression guard for issue #60. use-m@8.14.0 moved use.js/use.cjs/use.mjs
// under src/, which 404'd the long-standing CDN bootstrap URL
// https://unpkg.com/use-m/use.js (unpkg/jsdelivr serve raw files and ignore
// package.json "exports"). Consumers eval()'d the 404 body and got a cryptic
// "SyntaxError: Unexpected identifier 'found'".
//
// The fix restores root-level mirrors of src/use.* (generated by
// scripts/sync-root-entries.mjs). These tests assert the mirrors exist, stay in
// sync with src/, eval/import cleanly, and are shipped in the npm package.

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { describe, test, expect } from '../src/test-adapter.mjs';
import {
  ROOT_ENTRIES,
  renderRootEntry,
  buildRootEntry,
} from '../scripts/sync-root-entries.mjs';

const moduleName = `[${import.meta.url.split('.').pop()} module]`;
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const readRoot = (basename) => readFile(path.join(repoRoot, basename), 'utf8');
const readSrc = (basename) => readFile(path.join(repoRoot, 'src', basename), 'utf8');

describe(`${moduleName} root entry mirrors`, () => {
  test(`${moduleName} mirrors exactly src/use.js, src/use.cjs and src/use.mjs`, () => {
    expect(ROOT_ENTRIES).toEqual(['use.js', 'use.cjs', 'use.mjs']);
  });

  for (const basename of ['use.js', 'use.cjs', 'use.mjs']) {
    test(`${moduleName} ${basename} exists at the package root`, () => {
      expect(existsSync(path.join(repoRoot, basename))).toBe(true);
    });

    test(`${moduleName} root ${basename} is in sync with src/${basename}`, async () => {
      const [rootContent, expected] = await Promise.all([
        readRoot(basename),
        buildRootEntry(basename),
      ]);
      // If this fails, run `npm run sync:entries` after editing src/.
      expect(rootContent).toBe(expected);
    });

    test(`${moduleName} root ${basename} contains the full src/${basename} body`, async () => {
      const [rootContent, srcContent] = await Promise.all([
        readRoot(basename),
        readSrc(basename),
      ]);
      // Mirror = generated header + verbatim src body. The body must be present
      // untouched so the build behaves identically to src/.
      expect(rootContent.endsWith(srcContent)).toBe(true);
      expect(renderRootEntry(srcContent, basename)).toBe(rootContent);
    });
  }

  // The core regression: eval()'ing the root use.js (what the CDN bootstrap
  // does) must yield a working `use` function — never a SyntaxError.
  test(`${moduleName} root use.js eval()s to a working use function`, async () => {
    const source = await readRoot('use.js');
    // eslint-disable-next-line no-eval
    const exported = eval(source);
    expect(typeof exported.use).toBe('function');
    expect(typeof exported.use.all).toBe('function');
    expect(typeof exported.makeUse).toBe('function');
  });

  // The eval'd 404 body that broke consumers must NOT look like the module, so
  // the resilient loader's guard rejects it instead of eval()'ing it.
  test(`${moduleName} the 404 "Not found" body is not a valid module body`, async () => {
    const notFoundBody = 'Not found: /use-m@8.14.0/use.js';
    let syntaxError;
    try {
      // eslint-disable-next-line no-eval
      eval(notFoundBody);
    } catch (error) {
      syntaxError = error;
    }
    // Sanity-check that this is indeed the cryptic failure from the issue, and
    // that the restored mirror is the antidote.
    expect(syntaxError).toBeInstanceOf(SyntaxError);
    const realModule = await readRoot('use.js');
    expect(realModule.length).toBeGreaterThan(notFoundBody.length * 100);
  });

  test(`${moduleName} root use.mjs imports to a working use function`, async () => {
    const mod = await import(pathToFileURL(path.join(repoRoot, 'use.mjs')).href);
    expect(typeof mod.use).toBe('function');
  });

  test(`${moduleName} package.json ships the root mirrors and keeps src canonical`, async () => {
    const pkg = JSON.parse(await readFile(path.join(repoRoot, 'package.json'), 'utf8'));
    for (const basename of ROOT_ENTRIES) {
      expect(pkg.files).toContain(basename);
      expect(pkg.files).toContain(`src/${basename}`);
    }
    // use.cjs / use.mjs are real modules and stay reachable via the exports map;
    // use.js is eval-only and must NOT be advertised as an importable subpath.
    expect(pkg.exports['./use.cjs']).toBe('./src/use.cjs');
    expect(pkg.exports['./use.mjs']).toBe('./src/use.mjs');
    expect(pkg.exports['./use.js']).toBeUndefined();
  });
});
